#!/usr/bin/env bash
npm run build &&
rsync \
  --recursive \
  --verbose \
  --archive \
  --update \
  --delete \
  --prune-empty-dirs \
  --compress \
  ./public/* \
  pixelastic:/var/www/talks.pixelastic.com/slides/algolia-speaker-program-dailymotion-2017/
